/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include "addTwoNums.h"

 
int addTwoNumsfunc(CLIENT *clnt, int a, int b){
    operandos ops;
    int *result;

    ops.a=a;
    ops.b=b;
    result = addtwonums_1(&ops, clnt);

    if (result==NULL){
        fprintf(stderr, "Problema na chamada RPC\n");
        exit(0);
    }

    return *result;
}

 
 
int main (int argc, char *argv[]){

    CLIENT *clnt;
    int a,b;


    if (argc!=4) {
        fprintf(stderr,"Uso: %s hostname num1 num2\n",argv[0]);
        exit(0); 
    }
    
    clnt = clnt_create(argv[1], SUM_PROG, SUM_VERSAO, "udp");
    
    /* Garantindo a criacao da ligacao com o remoto */
    
    if (clnt == (CLIENT *) NULL) {
        clnt_pcreateerror(argv[1]);
        exit(1); 
    }
    
    /* Recupera os 2 operandos passados como argumento */
    
    a = atoi(argv[2]); b = atoi(argv[3]);
    
    printf("%d + %d = %d\n", a, b, addTwoNumsfunc(clnt,a,b));
    
    clnt_destroy(clnt);
    return(0);
}
 