/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

// #include "countwords.h"
// #include "stdio.h"
// #include "stdlib.h"

// void
// word_program_1(char *host)
// {
// 	CLIENT *clnt;
// 	char * *result_1;
// 	words  imprime_1_arg;
// 	void  *result_2;
// 	words  adiciona_1_arg;

// #ifndef	DEBUG
	// clnt = clnt_create (host, WORD_PROGRAM, WORD_VERSAO, "udp");
	// if (clnt == NULL) {
	// 	clnt_pcreateerror (host);
	// 	exit (1);
	// }
// #endif	/* DEBUG */

// 	result_1 = imprime_1(&imprime_1_arg, clnt);
// 	if (result_1 == (char **) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// 	result_2 = adiciona_1(&adiciona_1_arg, clnt);
// 	if (result_2 == (void *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// #ifndef	DEBUG
// 	clnt_destroy (clnt);
// #endif	 /* DEBUG */
// }

#include "countwords.h"
#include "stdio.h"
#include "stdlib.h"


void adicionaPalavra(CLIENT *clnt){


	char** word;

	scanf("%s", word);

	words listaWords = word;

	adiciona_1(listaWords, clnt);

}

void imprimirDicionario(CLIENT *clnt){


	imprime_1()

}


int
main (int argc, char *argv[])
{

	if (argc != 2){
		fprintf(stderr, "ERRO!\n");
		exit(0);
	}

	CLIENT* clnt = clnt_create (argv[1], WORD_PROGRAM, WORD_VERSAO, "udp");

	if (clnt == (CLIENT*) NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}

	/**
	 *  AQUI SERÁ A REGRA DE NEGOCIO !
	 */

	int opcao = 0;
	
	while (opcao != 10 )
	{
		/* code */
		opcao = imprimeMenu();
		
		switch (opcao)
		{	
			case 1:
				adicionaPalavra(clnt);
				break;

			case 2:
				imprimirDicionario(clnt);
				break;

			case 10:
				/* code */
				printf("Obrigado!\n\n");
				break;
		
			default:
				break;
		}
	}
	

	printf("Result: ", );
	
	clnt_destroy(clnt);
	return (0);
}
