/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "countwords.h"

bool_t
xdr_wordCounted (XDR *xdrs, wordCounted *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->word, MAX_WORD_LENGHT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_words (XDR *xdrs, words *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (wordCounted), (xdrproc_t) xdr_wordCounted))
		 return FALSE;
	return TRUE;
}
