/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNTWORDS_H_RPCGEN
#define _COUNTWORDS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_WORD_LENGHT 100
#define MAX_WORD 100

struct wordCounted {
	char word[MAX_WORD_LENGHT];
	int count;
};
typedef struct wordCounted wordCounted;

typedef wordCounted *words;

#define WORD_PROGRAM 5555555
#define WORD_VERSAO 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIME 1
extern  char ** imprime_1(words *, CLIENT *);
extern  char ** imprime_1_svc(words *, struct svc_req *);
#define ADICIONA 2
extern  void * adiciona_1(words *, CLIENT *);
extern  void * adiciona_1_svc(words *, struct svc_req *);
extern int word_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIME 1
extern  char ** imprime_1();
extern  char ** imprime_1_svc();
#define ADICIONA 2
extern  void * adiciona_1();
extern  void * adiciona_1_svc();
extern int word_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_wordCounted (XDR *, wordCounted*);
extern  bool_t xdr_words (XDR *, words*);

#else /* K&R C */
extern bool_t xdr_wordCounted ();
extern bool_t xdr_words ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNTWORDS_H_RPCGEN */
