/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "listaEncadeada.h"

bool_t
xdr_list (XDR *xdrs, list *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->prox, sizeof (list), (xdrproc_t) xdr_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_elem (XDR *xdrs, elem *objp)
{
	register int32_t *buf;

	 if (!xdr_list (xdrs, objp))
		 return FALSE;
	return TRUE;
}
