/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTAENCADEADA_H_RPCGEN
#define _LISTAENCADEADA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct list {
	int num;
	struct list *prox;
};
typedef struct list list;

typedef list elem;

#define PROG 55555555
#define VERSION 100

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT 1
extern  char ** print_100(void *, CLIENT *);
extern  char ** print_100_svc(void *, struct svc_req *);
#define SUM 2
extern  int * sum_100(void *, CLIENT *);
extern  int * sum_100_svc(void *, struct svc_req *);
#define ADD_LAST_ELEM 3
extern  void * add_last_elem_100(elem *, CLIENT *);
extern  void * add_last_elem_100_svc(elem *, struct svc_req *);
#define DELETE_LAST_ELEM 4
extern  void * delete_last_elem_100(void *, CLIENT *);
extern  void * delete_last_elem_100_svc(void *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT 1
extern  char ** print_100();
extern  char ** print_100_svc();
#define SUM 2
extern  int * sum_100();
extern  int * sum_100_svc();
#define ADD_LAST_ELEM 3
extern  void * add_last_elem_100();
extern  void * add_last_elem_100_svc();
#define DELETE_LAST_ELEM 4
extern  void * delete_last_elem_100();
extern  void * delete_last_elem_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_list (XDR *, list*);
extern  bool_t xdr_elem (XDR *, elem*);

#else /* K&R C */
extern bool_t xdr_list ();
extern bool_t xdr_elem ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LISTAENCADEADA_H_RPCGEN */
